[package]
authors = ["James Waples <jamwaffles@gmail.com>"]
categories = ["embedded", "no-std"]
description = "I2C driver for the SSH1106 OLED display controller"
documentation = "https://jamwaffles.github.io/ssh1106"
exclude = [".travis.yml", ".gitignore"]
keywords = ["no-std", "ssh1106", "oled", "embedded", "embedded-hal-driver"]
license = "MIT OR Apache-2.0"
name = "ssh1106"
readme = "README.md"
repository = "https://github.com/jamwaffles/ssh1106"
version = "0.2.2"
edition = "2018"
[badges.travis-ci]
branch = "master"
repository = "jamwaffles/ssh1106"

[dependencies]
embedded-hal = "0.2.2"

[dependencies.embedded-graphics]
optional = true
version = "0.4.4"

[dev-dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.6"
panic-semihosting = "0.5.1"

[dev-dependencies.stm32f103xx-hal]
features = ["rt"]
git = "https://github.com/japaric/stm32f103xx-hal.git"
rev = "d1bfbbf9148fc3b9d095fdb3f299aca4070531d8"
version = "*"

[features]
default = ["graphics"]
graphics = ["embedded-graphics"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
debug = true
lto = true
